# Generated by Django 4.2.3 on 2024-10-27 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '12. Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='internship_thumbnail/')),
                ('requirement', models.TextField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '3. Cource',
            },
        ),
        migrations.CreateModel(
            name='CourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '4. Cource Categories',
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '9. Roles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.TextField(null=True)),
                ('interested_category', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': '2. Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(null=True, upload_to='instructor_profile_img/')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '1. Teacher',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='training_thumbnail/')),
                ('duration', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courcecategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_training', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '13. Training',
            },
        ),
        migrations.CreateModel(
            name='TrainingChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('video', models.FileField(upload_to='training_videos/')),
                ('duration', models.IntegerField(null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_chapter', to='main.training')),
            ],
            options={
                'verbose_name_plural': '15. Training Videos',
            },
        ),
        migrations.CreateModel(
            name='StudentTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_training_student', to='main.student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_training', to='main.training')),
            ],
            options={
                'verbose_name_plural': '14. Student Training Enrollment',
            },
        ),
        migrations.CreateModel(
            name='StudentCourceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_cource', to='main.cource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='main.student')),
            ],
            options={
                'verbose_name_plural': '6. Student Cource Enrollment',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_subject', models.CharField(max_length=200, verbose_name='subject')),
                ('notif_for', models.CharField(max_length=200, verbose_name='detail')),
                ('notif_status', models.BooleanField(default=False, verbose_name='Status')),
                ('notif_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name_plural': '11. Notification',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'verbose_name_plural': '7. Student Favorite Cource',
            },
        ),
        migrations.AddField(
            model_name='cource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courcecategory'),
        ),
        migrations.AddField(
            model_name='cource',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_cource', to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('video', models.FileField(upload_to='internship_videos/')),
                ('duration', models.IntegerField(null=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cource_chapter', to='main.cource')),
            ],
            options={
                'verbose_name_plural': '5. Videos',
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(null=True, upload_to='blog_images/')),
                ('article1', models.TextField(null=True)),
                ('img2', models.ImageField(null=True, upload_to='blog_images/')),
                ('article2', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blogcategory')),
            ],
            options={
                'verbose_name_plural': '8. Blog',
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('detail', models.TextField(null=True)),
                ('student_status', models.BooleanField(default=False, null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '10. Assignments',
            },
        ),
    ]
