# Generated by Django 4.2.3 on 2024-10-30 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
