# Generated by Django 4.2.3 on 2024-10-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_login_via_opt_student_otp_digit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='login_via_opt',
            new_name='login_via_otp',
        ),
    ]
