# Generated by Django 4.2.3 on 2024-10-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_login_via_opt_student_login_via_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='login_via_opt',
            new_name='login_via_otp',
        ),
    ]
