# Generated by Django 4.2.3 on 2024-11-09 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_login_via_opt_teacher_login_via_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingchapter',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
