# Generated by Django 4.2.3 on 2024-11-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_trainingchapter_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingchapter',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
