# Generated by Django 4.2.3 on 2024-11-10 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trainingchapter_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAssignments',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('detail', models.TextField(null=True)),
                ('student_status', models.BooleanField(default=False, null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '10. Training Assignments',
            },
        ),
    ]
