# Generated by Django 4.2.3 on 2024-11-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_trainingassignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingchapter',
            name='duration',
        ),
    ]
