# Generated by Django 4.2.3 on 2024-11-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_trainingchapter_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='duration',
        ),
    ]
