# Generated by Django 4.2.3 on 2024-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_refercode_rename_qualification_student_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refercode',
            name='hr_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
