# Generated by Django 4.2.3 on 2024-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_refercode_hr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercode',
            name='code',
            field=models.IntegerField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
