# Generated by Django 4.2.3 on 2024-11-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_refercode_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refercode',
            options={'verbose_name_plural': '16. Refer Code'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.CharField(max_length=25)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cource')),
            ],
        ),
    ]
