# Generated by Django 4.2.3 on 2024-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_refercode_options_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercode',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
