# Generated by Django 4.2.3 on 2024-11-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_refercode_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '17. Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_product',
            field=models.CharField(max_length=100),
        ),
    ]
