# Generated by Django 4.2.3 on 2024-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_order_options_alter_order_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='login_via_otp',
            field=models.BooleanField(default=True),
        ),
    ]
